include: [".well-known"]
include: ["css"]

url: https://yt-downloader.xyz/

languages: ["en", "pl"]
exclude_from_localizations: ["assets", "CNAME","python"]
defaultLang: en
languageNames:
  pl: Polski
  en: English
