include: [".well-known"]
include: ["assets"]

url: https://yt-downloader.xyz/

languages: ["en", "pl"]
exclude_from_localizations: ["CNAME", "python"]
defaultLang: en
languageNames:
  pl: Polski
  en: English
